services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./../src:/var/www
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    depends_on:
      - php-fpm
      - redis
      - postgres
    networks:
      - app-network

  php-fpm:
    container_name: php
    build:
      context: "./dockerfiles/php/${PHP_VERSION}"
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
      - ./ini/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${PHP_FPM_PORT}:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - app-network


networks:
  app-network:
    driver: bridge